apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: c162r1t24-go 
  janus-idp.io/tekton: c162r1t24-go
  backstage.io/kubernetes-id: c162r1t24-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c162r1t24-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml