apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: c162r1t24-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c162r1t24-go 
  name: c162r1t24-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: c162r1t24-go 
